### ISSUE TITLE
When does templates know there is a new version?

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/dashboard-utils#1]
![image](https://user-images.githubusercontent.com/1987296/214700338-587c2071-74f2-49d3-b6cc-ce60e29960fd.png)

**Comment by adamdriscoll** [comment]
There is some sort of cache in the ims.com website. We need to invalidate it when a new version is published.

**Comment by adamdriscoll** [comment]
Cache wasn't being invalidated or expired. This is now fixed. New updates will show immediately.
